### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by AlexNaga** [iotics-live/iotics-Controller#12]
Iotics version: 0.12.95

```
[Mon May 12 08:26:39 CEST 2025] If there are issue with add-on startup, please submit an issue https://github.com/iotics-live/iotics-Controller with the output below
[Mon May 12 08:26:39 CEST 2025] /share/iotics/mysql exists
[Mon May 12 08:26:39 CEST 2025] Link MariaDB to share folder...
[Mon May 12 08:26:39 CEST 2025] Start MariaDB...
Starting MariaDB database server: mariadbd . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
250512 08:27:29 mysqld_safe Logging to '/tmp/tmp.bjJ14rfR2d.err'.
250512 08:27:29 mysqld_safe Can't log to error log and syslog at the same time.  Remove all --log-error configuration options for --syslog to take effect.
250512 08:27:30 mysqld_safe Starting mariadbd daemon with databases from /var/lib/mysql
Running '/etc/init.d/mariadb start' failed with error log:
250512 08:27:30 mysqld_safe Starting mariadbd daemon with databases from /var/lib/mysql
2025-05-12  8:27:30 0 [Note] Starting MariaDB 10.11.11-MariaDB-0+deb12u1 source revision e69f8cae1a15e15b9e4f5e0f8497e1f17bdc81a4 server_uid 5AymU12wIrnIGBxs19AMT5BwTx8= as process 589
250512 08:27:31 mysqld_safe mysqld from pid file /run/mysqld/mysqld.pid ended
 failed!
[Mon May 12 08:27:31 CEST 2025] Waiting for MariaDB to start...
[Mon May 12 08:27:32 CEST 2025] Waiting for MariaDB to be ready... (0/30)
[Mon May 12 08:27:35 CEST 2025] Waiting for MariaDB to be ready... (1/30)
[Mon May 12 08:27:37 CEST 2025] Waiting for MariaDB to be ready... (2/30)
[Mon May 12 08:27:39 CEST 2025] Waiting for MariaDB to be ready... (3/30)
[Mon May 12 08:27:41 CEST 2025] Waiting for MariaDB to be ready... (4/30)
[Mon May 12 08:27:43 CEST 2025] Waiting for MariaDB to be ready... (5/30)
[Mon May 12 08:27:45 CEST 2025] Waiting for MariaDB to be ready... (6/30)
[Mon May 12 08:27:47 CEST 2025] Waiting for MariaDB to be ready... (7/30)
[Mon May 12 08:27:49 CEST 2025] Waiting for MariaDB to be ready... (8/30)
[Mon May 12 08:27:51 CEST 2025] Waiting for MariaDB to be ready... (9/30)
[Mon May 12 08:27:53 CEST 2025] Waiting for MariaDB to be ready... (10/30)
[Mon May 12 08:27:55 CEST 2025] Waiting for MariaDB to be ready... (11/30)
Killed
[Mon May 12 08:29:37 CEST 2025] If there are issue with add-on startup, please submit an issue https://github.com/iotics-live/iotics-Controller with the output below
[Mon May 12 08:29:37 CEST 2025] /share/iotics/mysql exists
[Mon May 12 08:29:37 CEST 2025] Link MariaDB to share folder...
[Mon May 12 08:29:38 CEST 2025] Start MariaDB...
Starting MariaDB database server: mariadbd . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
250512 08:30:34 mysqld_safe Can't log to error log and syslog at the same time.  Remove all --log-error configuration options for --syslog to take effect.
250512 08:30:34 mysqld_safe Logging to '/tmp/tmp.ciEpoL0CwD.err'.
250512 08:30:35 mysqld_safe Starting mariadbd daemon with databases from /var/lib/mysql
Running '/etc/init.d/mariadb start' failed with error log:
250512 08:30:35 mysqld_safe Starting mariadbd daemon with databases from /var/lib/mysql
2025-05-12  8:30:35 0 [Note] Starting MariaDB 10.11.11-MariaDB-0+deb12u1 source revision e69f8cae1a15e15b9e4f5e0f8497e1f17bdc81a4 server_uid 6r5LueyrPzoD1hKCZ4tC+oIMaHE= as process 588
2025-05-12  8:30:35 0 [Note] InnoDB: Compressed tables use zlib 1.2.13
2025-05-12  8:30:35 0 [Note] InnoDB: Number of transaction pools: 1
2025-05-12  8:30:35 0 [Note] InnoDB: Using ARMv8 crc32 instructions
2025-05-12  8:30:35 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
2025-05-12  8:30:35 0 [Warning] mariadbd: io_uring_queue_init() failed with errno 95
2025-05-12  8:30:35 0 [Warning] InnoDB: liburing disabled: falling back to innodb_use_native_aio=OFF
2025-05-12  8:30:35 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2025-05-12  8:30:35 0 [Note] InnoDB: Completed initialization of buffer pool
2025-05-12  8:30:35 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
2025-05-12  8:30:37 0 [Note] InnoDB: End of log at LSN=46862
2025-05-12  8:30:37 0 [Note] InnoDB: 128 rollback segments are active.
2025-05-12  8:30:38 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
2025-05-12  8:30:38 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
2025-05-12  8:30:38 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
250512 08:30:38 mysqld_safe mysqld from pid file /run/mysqld/mysqld.pid ended
 failed!
[Mon May 12 08:30:39 CEST 2025] Waiting for MariaDB to start...
[Mon May 12 08:30:40 CEST 2025] Waiting for MariaDB to be ready... (0/30)
[Mon May 12 08:30:42 CEST 2025] Waiting for MariaDB to be ready... (1/30)
[Mon May 12 08:30:44 CEST 2025] Waiting for MariaDB to be ready... (2/30)
[Mon May 12 08:30:46 CEST 2025] Waiting for MariaDB to be ready... (3/30)
[Mon May 12 08:30:48 CEST 2025] Waiting for MariaDB to be ready... (4/30)
[Mon May 12 08:30:50 CEST 2025] Waiting for MariaDB to be ready... (5/30)
[Mon May 12 08:30:53 CEST 2025] Waiting for MariaDB to be ready... (6/30)
[Mon May 12 08:30:55 CEST 2025] Waiting for MariaDB to be ready... (7/30)
[Mon May 12 08:30:57 CEST 2025] Waiting for MariaDB to be ready... (8/30)
[Mon May 12 08:30:59 CEST 2025] Waiting for MariaDB to be ready... (9/30)
[Mon May 12 08:31:01 CEST 2025] Waiting for MariaDB to be ready... (10/30)
[Mon May 12 08:31:03 CEST 2025] Waiting for MariaDB to be ready... (11/30)
[Mon May 12 08:31:05 CEST 2025] Waiting for MariaDB to be ready... (12/30)
[Mon May 12 08:31:07 CEST 2025] Waiting for MariaDB to be ready... (13/30)
[Mon May 12 08:31:09 CEST 2025] Waiting for MariaDB to be ready... (14/30)
[Mon May 12 08:31:11 CEST 2025] Waiting for MariaDB to be ready... (15/30)
[Mon May 12 08:31:13 CEST 2025] Waiting for MariaDB to be ready... (16/30)
[Mon May 12 08:31:15 CEST 2025] Waiting for MariaDB to be ready... (17/30)
[Mon May 12 08:31:17 CEST 2025] Waiting for MariaDB to be ready... (18/30)
[Mon May 12 08:31:19 CEST 2025] Waiting for MariaDB to be ready... (19/30)
[Mon May 12 08:31:21 CEST 2025] Waiting for MariaDB to be ready... (20/30)
[Mon May 12 08:31:23 CEST 2025] Waiting for MariaDB to be ready... (21/30)
[Mon May 12 08:31:25 CEST 2025] Waiting for MariaDB to be ready... (22/30)
[Mon May 12 08:31:27 CEST 2025] Waiting for MariaDB to be ready... (23/30)
[Mon May 12 08:31:29 CEST 2025] Waiting for MariaDB to be ready... (24/30)
[Mon May 12 08:31:31 CEST 2025] Waiting for MariaDB to be ready... (25/30)
[Mon May 12 08:31:33 CEST 2025] Waiting for MariaDB to be ready... (26/30)
[Mon May 12 08:31:35 CEST 2025] Waiting for MariaDB to be ready... (27/30)
[Mon May 12 08:31:38 CEST 2025] Waiting for MariaDB to be ready... (28/30)
[Mon May 12 08:31:40 CEST 2025] Waiting for MariaDB to be ready... (29/30)
[Mon May 12 08:31:42 CEST 2025] ERROR: MariaDB failed to start properly within the time limit.
[Mon May 12 08:31:42 CEST 2025] Checking MariaDB status...
MariaDB is stopped..
[Mon May 12 08:31:43 CEST 2025] Checking if socket file exists...
total 8
```

**Comment by aajmarafi** [comment]
Hi Alex,

We've released a new controller update (version 12.97), which includes additional logging features to assist with troubleshooting.

Please follow the same steps as before to install the updated controller from the app. Once installed, send us the logs again so we can continue investigating the issue.

Regards,

Ali

**Comment by AlexNaga** [comment]
> Hi Alex,
> 
> We've released a new controller update (version 12.97), which includes additional logging features to assist with troubleshooting.
> 
> Please follow the same steps as before to install the updated controller from the app. Once installed, send us the logs again so we can continue investigating the issue.
> 
> Regards,
> 
> Ali

It seems as MariaDB started successfully now since latest update.

```
[Tue May 20 08:13:33 CEST 2025] If there are issue with add-on startup, please submit an issue https://github.com/iotics-live/iotics-Controller with the output below
[Tue May 20 08:13:33 CEST 2025] /share/iotics/mysql exists
[Tue May 20 08:13:33 CEST 2025] Link MariaDB to share folder...
[Tue May 20 08:13:34 CEST 2025] Start MariaDB...
Starting MariaDB database server: mariadbd . ..
[Tue May 20 08:13:39 CEST 2025] Waiting for MariaDB to start...
mysqld is alive
[Tue May 20 08:13:39 CEST 2025] MariaDB started successfully!
[Tue May 20 08:13:39 CEST 2025] Upgrade MariaDB...
This installation of MariaDB is already upgraded to 10.11.11-MariaDB.
There is no need to run mysql_upgrade again for 10.11.11-MariaDB.
You can use --force if you still want to run mysql_upgrade
[Tue May 20 08:13:40 CEST 2025] Create database...
[Tue May 20 08:13:40 CEST 2025] Start Nginx...
Starting nginx: nginx.
[Tue May 20 08:13:40 CEST 2025] Create cron to call container...
Starting periodic command scheduler: cron.
[Tue May 20 08:13:41 CEST 2025] Start the application...
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed. For more information go to https://aka.ms/aspnet/dataprotectionwarning
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {3819a2c1-e18f-4a46-8939-d7327d8a0c9d} may be persisted to storage in unencrypted form.
warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
      Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://*:8095'.
warn: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[16]
      The WebRootPath was not found: /app/wwwroot. Static files may be unavailable.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:8095
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
/run.sh: line 75:   277 Killed                  dotnet Iotics.Api.dll
```

**Comment by aajmarafi** [comment]
> > Hi Alex,
> > We've released a new controller update (version 12.97), which includes additional logging features to assist with troubleshooting.
> > Please follow the same steps as before to install the updated controller from the app. Once installed, send us the logs again so we can continue investigating the issue.
> > Regards,
> > Ali
> 
> It seems as MariaDB started successfully now since latest update.
> 
> ```
> [Tue May 20 08:13:33 CEST 2025] If there are issue with add-on startup, please submit an issue https://github.com/iotics-live/iotics-Controller with the output below
> [Tue May 20 08:13:33 CEST 2025] /share/iotics/mysql exists
> [Tue May 20 08:13:33 CEST 2025] Link MariaDB to share folder...
> [Tue May 20 08:13:34 CEST 2025] Start MariaDB...
> Starting MariaDB database server: mariadbd . ..
> [Tue May 20 08:13:39 CEST 2025] Waiting for MariaDB to start...
> mysqld is alive
> [Tue May 20 08:13:39 CEST 2025] MariaDB started successfully!
> [Tue May 20 08:13:39 CEST 2025] Upgrade MariaDB...
> This installation of MariaDB is already upgraded to 10.11.11-MariaDB.
> There is no need to run mysql_upgrade again for 10.11.11-MariaDB.
> You can use --force if you still want to run mysql_upgrade
> [Tue May 20 08:13:40 CEST 2025] Create database...
> [Tue May 20 08:13:40 CEST 2025] Start Nginx...
> Starting nginx: nginx.
> [Tue May 20 08:13:40 CEST 2025] Create cron to call container...
> Starting periodic command scheduler: cron.
> [Tue May 20 08:13:41 CEST 2025] Start the application...
> warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
>       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed. For more information go to https://aka.ms/aspnet/dataprotectionwarning
> warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
>       No XML encryptor configured. Key {3819a2c1-e18f-4a46-8939-d7327d8a0c9d} may be persisted to storage in unencrypted form.
> warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
>       Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://*:8095'.
> warn: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[16]
>       The WebRootPath was not found: /app/wwwroot. Static files may be unavailable.
> info: Microsoft.Hosting.Lifetime[14]
>       Now listening on: http://[::]:8095
> info: Microsoft.Hosting.Lifetime[0]
>       Application started. Press Ctrl+C to shut down.
> info: Microsoft.Hosting.Lifetime[0]
>       Hosting environment: Production
> info: Microsoft.Hosting.Lifetime[0]
>       Content root path: /app
> /run.sh: line 75:   277 Killed                  dotnet Iotics.Api.dll
> ```

That’s great news, Alex. Please let us know if you notice anything else unusual with the software/controller. 

Thanks!

**Comment by AlexNaga** [comment]
> > > Hi Alex,
> > > We've released a new controller update (version 12.97), which includes additional logging features to assist with troubleshooting.
> > > Please follow the same steps as before to install the updated controller from the app. Once installed, send us the logs again so we can continue investigating the issue.
> > > Regards,
> > > Ali
> > 
> > 
> > It seems as MariaDB started successfully now since latest update.
> > ```
> > [Tue May 20 08:13:33 CEST 2025] If there are issue with add-on startup, please submit an issue https://github.com/iotics-live/iotics-Controller with the output below
> > [Tue May 20 08:13:33 CEST 2025] /share/iotics/mysql exists
> > [Tue May 20 08:13:33 CEST 2025] Link MariaDB to share folder...
> > [Tue May 20 08:13:34 CEST 2025] Start MariaDB...
> > Starting MariaDB database server: mariadbd . ..
> > [Tue May 20 08:13:39 CEST 2025] Waiting for MariaDB to start...
> > mysqld is alive
> > [Tue May 20 08:13:39 CEST 2025] MariaDB started successfully!
> > [Tue May 20 08:13:39 CEST 2025] Upgrade MariaDB...
> > This installation of MariaDB is already upgraded to 10.11.11-MariaDB.
> > There is no need to run mysql_upgrade again for 10.11.11-MariaDB.
> > You can use --force if you still want to run mysql_upgrade
> > [Tue May 20 08:13:40 CEST 2025] Create database...
> > [Tue May 20 08:13:40 CEST 2025] Start Nginx...
> > Starting nginx: nginx.
> > [Tue May 20 08:13:40 CEST 2025] Create cron to call container...
> > Starting periodic command scheduler: cron.
> > [Tue May 20 08:13:41 CEST 2025] Start the application...
> > warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
> >       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed. For more information go to https://aka.ms/aspnet/dataprotectionwarning
> > warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
> >       No XML encryptor configured. Key {3819a2c1-e18f-4a46-8939-d7327d8a0c9d} may be persisted to storage in unencrypted form.
> > warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
> >       Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://*:8095'.
> > warn: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[16]
> >       The WebRootPath was not found: /app/wwwroot. Static files may be unavailable.
> > info: Microsoft.Hosting.Lifetime[14]
> >       Now listening on: http://[::]:8095
> > info: Microsoft.Hosting.Lifetime[0]
> >       Application started. Press Ctrl+C to shut down.
> > info: Microsoft.Hosting.Lifetime[0]
> >       Hosting environment: Production
> > info: Microsoft.Hosting.Lifetime[0]
> >       Content root path: /app
> > /run.sh: line 75:   277 Killed                  dotnet Iotics.Api.dll
> > ```
> 
> That’s great news, Alex. Please let us know if you notice anything else unusual with the software/controller.
> 
> Thanks!

Even though MariaDB now starts the addon still fails to start.

The last printed log: /run.sh: line 75:   277 Killed

**Comment by aajmarafi** [comment]
> > > > Hi Alex,
> > > > We've released a new controller update (version 12.97), which includes additional logging features to assist with troubleshooting.
> > > > Please follow the same steps as before to install the updated controller from the app. Once installed, send us the logs again so we can continue investigating the issue.
> > > > Regards,
> > > > Ali
> > > 
> > > 
> > > It seems as MariaDB started successfully now since latest update.
> > > ```
> > > [Tue May 20 08:13:33 CEST 2025] If there are issue with add-on startup, please submit an issue https://github.com/iotics-live/iotics-Controller with the output below
> > > [Tue May 20 08:13:33 CEST 2025] /share/iotics/mysql exists
> > > [Tue May 20 08:13:33 CEST 2025] Link MariaDB to share folder...
> > > [Tue May 20 08:13:34 CEST 2025] Start MariaDB...
> > > Starting MariaDB database server: mariadbd . ..
> > > [Tue May 20 08:13:39 CEST 2025] Waiting for MariaDB to start...
> > > mysqld is alive
> > > [Tue May 20 08:13:39 CEST 2025] MariaDB started successfully!
> > > [Tue May 20 08:13:39 CEST 2025] Upgrade MariaDB...
> > > This installation of MariaDB is already upgraded to 10.11.11-MariaDB.
> > > There is no need to run mysql_upgrade again for 10.11.11-MariaDB.
> > > You can use --force if you still want to run mysql_upgrade
> > > [Tue May 20 08:13:40 CEST 2025] Create database...
> > > [Tue May 20 08:13:40 CEST 2025] Start Nginx...
> > > Starting nginx: nginx.
> > > [Tue May 20 08:13:40 CEST 2025] Create cron to call container...
> > > Starting periodic command scheduler: cron.
> > > [Tue May 20 08:13:41 CEST 2025] Start the application...
> > > warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
> > >       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed. For more information go to https://aka.ms/aspnet/dataprotectionwarning
> > > warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
> > >       No XML encryptor configured. Key {3819a2c1-e18f-4a46-8939-d7327d8a0c9d} may be persisted to storage in unencrypted form.
> > > warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
> > >       Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://*:8095'.
> > > warn: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[16]
> > >       The WebRootPath was not found: /app/wwwroot. Static files may be unavailable.
> > > info: Microsoft.Hosting.Lifetime[14]
> > >       Now listening on: http://[::]:8095
> > > info: Microsoft.Hosting.Lifetime[0]
> > >       Application started. Press Ctrl+C to shut down.
> > > info: Microsoft.Hosting.Lifetime[0]
> > >       Hosting environment: Production
> > > info: Microsoft.Hosting.Lifetime[0]
> > >       Content root path: /app
> > > /run.sh: line 75:   277 Killed                  dotnet Iotics.Api.dll
> > > ```
> > 
> > 
> > That’s great news, Alex. Please let us know if you notice anything else unusual with the software/controller.
> > Thanks!
> 
> Even though MariaDB now starts the addon still fails to start.
> 
> The last printed log: /run.sh: line 75: 277 Killed

Hi again,

Our developer will review the new logs to investigate what’s going on.

In the meantime, I wanted to highlight a few important points you may have missed:

1- Make sure you are using HAOS (Home Assistant Operating System).

2- Avoid using a virtual machine, as the integration only supports Home Assistant OS and there is no HAOS version for VM environments.

3- We recommend using an AMD x86 architecture. While this is not mandatory, it is more common and generally more reliable for compatibility.

Thanks

**Comment by aajmarafi** [comment]
> > > > > Hi Alex,
> > > > > We've released a new controller update (version 12.97), which includes additional logging features to assist with troubleshooting.
> > > > > Please follow the same steps as before to install the updated controller from the app. Once installed, send us the logs again so we can continue investigating the issue.
> > > > > Regards,
> > > > > Ali
> > > > 
> > > > 
> > > > It seems as MariaDB started successfully now since latest update.
> > > > ```
> > > > [Tue May 20 08:13:33 CEST 2025] If there are issue with add-on startup, please submit an issue https://github.com/iotics-live/iotics-Controller with the output below
> > > > [Tue May 20 08:13:33 CEST 2025] /share/iotics/mysql exists
> > > > [Tue May 20 08:13:33 CEST 2025] Link MariaDB to share folder...
> > > > [Tue May 20 08:13:34 CEST 2025] Start MariaDB...
> > > > Starting MariaDB database server: mariadbd . ..
> > > > [Tue May 20 08:13:39 CEST 2025] Waiting for MariaDB to start...
> > > > mysqld is alive
> > > > [Tue May 20 08:13:39 CEST 2025] MariaDB started successfully!
> > > > [Tue May 20 08:13:39 CEST 2025] Upgrade MariaDB...
> > > > This installation of MariaDB is already upgraded to 10.11.11-MariaDB.
> > > > There is no need to run mysql_upgrade again for 10.11.11-MariaDB.
> > > > You can use --force if you still want to run mysql_upgrade
> > > > [Tue May 20 08:13:40 CEST 2025] Create database...
> > > > [Tue May 20 08:13:40 CEST 2025] Start Nginx...
> > > > Starting nginx: nginx.
> > > > [Tue May 20 08:13:40 CEST 2025] Create cron to call container...
> > > > Starting periodic command scheduler: cron.
> > > > [Tue May 20 08:13:41 CEST 2025] Start the application...
> > > > warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
> > > >       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed. For more information go to https://aka.ms/aspnet/dataprotectionwarning
> > > > warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
> > > >       No XML encryptor configured. Key {3819a2c1-e18f-4a46-8939-d7327d8a0c9d} may be persisted to storage in unencrypted form.
> > > > warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
> > > >       Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://*:8095'.
> > > > warn: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[16]
> > > >       The WebRootPath was not found: /app/wwwroot. Static files may be unavailable.
> > > > info: Microsoft.Hosting.Lifetime[14]
> > > >       Now listening on: http://[::]:8095
> > > > info: Microsoft.Hosting.Lifetime[0]
> > > >       Application started. Press Ctrl+C to shut down.
> > > > info: Microsoft.Hosting.Lifetime[0]
> > > >       Hosting environment: Production
> > > > info: Microsoft.Hosting.Lifetime[0]
> > > >       Content root path: /app
> > > > /run.sh: line 75:   277 Killed                  dotnet Iotics.Api.dll
> > > > ```
> > > 
> > > 
> > > That’s great news, Alex. Please let us know if you notice anything else unusual with the software/controller.
> > > Thanks!
> > 
> > 
> > Even though MariaDB now starts the addon still fails to start.
> > The last printed log: /run.sh: line 75: 277 Killed
> 
> Hi again,
> 
> Our developer will review the new logs to investigate what’s going on.
> 
> In the meantime, I wanted to highlight a few important points you may have missed:
> 
> 1- Make sure you are using HAOS (Home Assistant Operating System).
> 
> 2- Avoid using a virtual machine, as the integration only supports Home Assistant OS and there is no HAOS version for VM environments.
> 
> 3- We recommend using an AMD x86 architecture. While this is not mandatory, it is more common and generally more reliable for compatibility.
> 
> Thanks

**Comment by aajmarafi** [comment]
Hey AlexNaga,

Can you share the full logs in a txt file?

**Comment by aajmarafi** [comment]
> > > > Hi Alex,
> > > > We've released a new controller update (version 12.97), which includes additional logging features to assist with troubleshooting.
> > > > Please follow the same steps as before to install the updated controller from the app. Once installed, send us the logs again so we can continue investigating the issue.
> > > > Regards,
> > > > Ali
> > > 
> > > 
> > > It seems as MariaDB started successfully now since latest update.
> > > ```
> > > [Tue May 20 08:13:33 CEST 2025] If there are issue with add-on startup, please submit an issue https://github.com/iotics-live/iotics-Controller with the output below
> > > [Tue May 20 08:13:33 CEST 2025] /share/iotics/mysql exists
> > > [Tue May 20 08:13:33 CEST 2025] Link MariaDB to share folder...
> > > [Tue May 20 08:13:34 CEST 2025] Start MariaDB...
> > > Starting MariaDB database server: mariadbd . ..
> > > [Tue May 20 08:13:39 CEST 2025] Waiting for MariaDB to start...
> > > mysqld is alive
> > > [Tue May 20 08:13:39 CEST 2025] MariaDB started successfully!
> > > [Tue May 20 08:13:39 CEST 2025] Upgrade MariaDB...
> > > This installation of MariaDB is already upgraded to 10.11.11-MariaDB.
> > > There is no need to run mysql_upgrade again for 10.11.11-MariaDB.
> > > You can use --force if you still want to run mysql_upgrade
> > > [Tue May 20 08:13:40 CEST 2025] Create database...
> > > [Tue May 20 08:13:40 CEST 2025] Start Nginx...
> > > Starting nginx: nginx.
> > > [Tue May 20 08:13:40 CEST 2025] Create cron to call container...
> > > Starting periodic command scheduler: cron.
> > > [Tue May 20 08:13:41 CEST 2025] Start the application...
> > > warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
> > >       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed. For more information go to https://aka.ms/aspnet/dataprotectionwarning
> > > warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
> > >       No XML encryptor configured. Key {3819a2c1-e18f-4a46-8939-d7327d8a0c9d} may be persisted to storage in unencrypted form.
> > > warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
> > >       Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://*:8095'.
> > > warn: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[16]
> > >       The WebRootPath was not found: /app/wwwroot. Static files may be unavailable.
> > > info: Microsoft.Hosting.Lifetime[14]
> > >       Now listening on: http://[::]:8095
> > > info: Microsoft.Hosting.Lifetime[0]
> > >       Application started. Press Ctrl+C to shut down.
> > > info: Microsoft.Hosting.Lifetime[0]
> > >       Hosting environment: Production
> > > info: Microsoft.Hosting.Lifetime[0]
> > >       Content root path: /app
> > > /run.sh: line 75:   277 Killed                  dotnet Iotics.Api.dll
> > > ```
> > 
> > 
> > That’s great news, Alex. Please let us know if you notice anything else unusual with the software/controller.
> > Thanks!
> 
> Even though MariaDB now starts the addon still fails to start.
> 
> The last printed log: /run.sh: line 75: 277 Killed

Hey AlexNaga,

Can you share the full logs in a txt file?
